In [ ]:
#APRENDIENDO A USAR NUMPY para vectores

import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos de una dimensión
array_basico #mostrar todo el array

array_basico[0] #pedir la posición 0 del array

array_basico[0]=10 #reemplazar la posición 0 a otro valor, en este caso 10
array_basico




array([10,  2,  3,  4,  5])

In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos

array_basico = array_basico * 1.6
print("este es el nuevo valor del array multiplocado por 1.6: ", array_basico)

este es el nuevo valor del array multiplocado por 1.6:  [1.6 3.2 4.8 6.4 8. ]


In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos

print("este es el valor más grande: ", array_basico.max())

este es el valor más grande:  5


In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos

print("este es el valor minimo: ", array_basico.min())

este es el valor minimo:  1


In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos

print("esta es la suma de todos los valores en el array: ", array_basico.sum())

esta es la suma de todos los valores en el array:  15


In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos

print("muestra los datos desde la posición 2 en adelante: ", array_basico[:2])

muestra los datos desde la posición 2 en adelante:  [1 2]


In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos

print("muestra los datos desde la posición 3 hacia atrás: ", array_basico[3:])

muestra los datos desde la posición 3 hacia atrás:  [4 5]


In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([1,2,3,4,5]) #hacer un array de datos

array_basico[:] = 99
print("cambia todos los datos : ", array_basico)

cambia todos los datos :  [99 99 99 99 99]


In [ ]:
import numpy as np #importar la libreria numpy para hacer arrays

array_basico = np.array([[1,2],[3,4],[4,5],[5,6]]) #hacer un array de datos  de 2 dimensiones
array_basico

array([[1, 2],
       [3, 4],
       [4, 5],
       [5, 6]])

In [ ]:
#axis 0 son columnas arriba a abajo
#axis 1 son filas izquierda a derecha

In [ ]:
basico_multidimensional = np.array([[1,2,3,4],[5,6,7,8]]) #filas 2 columnas 4
basico_multidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #filas 2 columnas 4
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #filas 2 columnas 4
array[1] #muestra la fila 1, iniciando desde 0

array([5, 6, 7, 8])

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #filas 2 columnas 4
array[1,2] #muestra la fila 1, columna 2

7

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #filas 2 columnas 4
array[:2,1:] #muestra todo desde el inicio hasta la fila 2, luego muestra todo excepto la columna 1

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #filas 2 columnas 4


In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array.max(axis=0) #muestra el valor mayor de cada columna

array([ 9, 10, 11, 12])

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array.max(axis=1) #muestra el valor mayor de cada fila

array([ 4,  8, 12])

In [ ]:
#PANDAS para leer tipos de archivo como CSV, Excel, JSON, HTML, SQL

import pandas as pd

fotball_dicc = {
    "player": ["Lionel Messi", "Cristiano Ronaldo"], #clave, valor
    "year": [2016, 2017],
    "goals": [37,25]
}

data = pd.DataFrame(fotball_dicc) #pd.DataFrame convertir a filas y columnas
print(data)

              player  year  goals
0       Lionel Messi  2016     37
1  Cristiano Ronaldo  2017     25


In [ ]:
#Conectarse a Google Drive para leer el Dataframe

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

import plotly.express as px

path_file="/content/drive/MyDrive/AUNAR/paralaclase3.csv"
df=pd.read_csv(path_file, sep=",", header=1)
print(df.tail(n))



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


NameError: name 'n' is not defined

In [ ]:
#Conectarse a Google Drive para leer el Dataframe

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

import plotly.express as px

path_file="/content/drive/MyDrive/AUNAR/paralaclase3.csv"
df=pd.read_csv(path_file, sep=",", header=1)
n = 2  # Define the number of rows to display
print(df.tail(n))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
     Juan;Mauricio;22;190
2  Manuel;Leonardo;11;190
3   Nicolas;Daniel;44;130


In [ ]:
#Conectarse a Google Drive para leer el Dataframe

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

import plotly.express as px

path_file="/content/drive/MyDrive/AUNAR/paralaclase3.csv"
df=pd.read_csv(path_file, sep=",", header=1)
n = 2  # Define the number of rows to display
print(df.describe)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<bound method NDFrame.describe of      Juan;Mauricio;22;190
0   Erick;Neurisma;15;160
1  Judas;Escariote;80;175
2  Manuel;Leonardo;11;190
3   Nicolas;Daniel;44;130>


In [ ]:
data.colums #leer todos los nombres de las columnas
data.columns = ['id', 'genero'] #asignar nombre a las columnas

In [ ]:
#Conectarse a Google Drive para leer el Dataframe

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

import plotly.express as px

path_file="/content/drive/MyDrive/AUNAR/paralaclase3.csv"
df=pd.read_csv(path_file, sep=",", header=1)
data.info() #mostrar información del archivo

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   player  2 non-null      object
 1   year    2 non-null      int64 
 2   goals   2 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes


In [ ]:
#Conectarse a Google Drive para leer el Dataframe

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

import plotly.express as px

path_file="/content/drive/MyDrive/AUNAR/paralaclase3.csv"
df=pd.read_csv(path_file, sep=",", header=1)
n = 2  # Define the number of rows to display

data['nombre1 '] #para conocer la información de una sola columna

data['nombre1 '].unique() #para conocer los valores unicos de una columna

data['nombre1 '].count() #cuenta la candidad de registros en la columna

data['nombre1 '].value_counts #cuenta la cantidad de registros por cada valor unico

data.sort_values('x columna' , 'y columna') #ordena los valores por x columna

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


KeyError: 'nombre1 '

In [ ]:
#Conectarse a Google Drive para leer el Dataframe

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

import plotly.express as px

path_file="/content/drive/MyDrive/AUNAR/paralaclase3.csv"
df=pd.read_csv(path_file, sep=",", header=1)

MessageError: Error: credential propagation was unsuccessful